version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly, day: monday, time: '04:00', timezone: America/Denver }
    open-pull-requests-limit: 10
    groups:
      production:
        dependency-type: production
        applies-to: version-updates
        update-types: [minor, patch]
      development:
        dependency-type: development
        applies-to: version-updates
        update-types: [minor, patch]
    labels: [dependencies, security]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    labels: [dependencies, ci]
