WITH params(label, state, city, contractor_name) AS (
  VALUES
    ('CO_00', 'CO', 'Denver', 'PLAZA CONSTRUCTION, INC.'),
    ('CO_01', 'CO', 'Denver', 'THE SPITZER ELECTRICAL COMPANY'),
    ('CO_02', 'CO', 'Centennial', 'CASTLE ROCK CONSTRUCTION COMPANY OF COLORADO, LLC'),
    ('CO_03', 'CO', 'Centennial', 'Earthwood Custom Remodeling, Inc.'),
    ('CO_04', 'CO', 'Centennial', 'Harmonic Construction Services, Incorporated'),
    ('CO_05', 'CO', 'Aurora', 'Freund Construction Management, LLC'),
    ('CO_06', 'CO', 'Wheat Ridge', 'WH Construction LLC dba Republic Garage'),
    ('CO_07', 'CO', 'Denver', 'CENTURY BUILDERS CORP.'),
    ('CO_08', 'CO', 'Denver', 'WOLFDAISY CONSTRUCTION INC.'),
    ('CO_09', 'CO', 'Centennial', 'Bulldog Construction and Landscaping'),
    ('CO_10', 'CO', 'Arvada', 'LORENZO''S CONCRETE LLC'),
    ('CO_11', 'CO', 'Wheat Ridge', 'HIGHLANDS PLUMBING, LLC'),
    ('CO_12', 'CO', 'Centennial', 'WABASH CONSTRUCTION COMPANY, LLC'),
    ('CO_13', 'CO', 'Denver', 'ROSEWATER CONSTRUCTION, INC.'),
    ('CO_14', 'CO', 'DENVER', 'A-NATIVE SPRINKLERS & LANDSCAPING L.L.C.'),
    ('CO_15', 'CO', 'Lakewood', 'MAJESTIC LANDSCAPING INC.'),
    ('CO_16', 'CO', 'Denver', 'Rodney Stein Construction LLC'),
    ('CO_17', 'CO', 'Aurora', 'AURORA-HUDDLESTON PLUMBING, INC.'),
    ('CO_18', 'CO', 'Denver', 'B-Line Construction Services Inc.'),
    ('CO_19', 'CO', 'Englewood', 'HAWKINS ELECTRICAL SERVICE COMPANY'),
    ('CO_20', 'CO', 'Denver', 'Young Electrical Services LLC'),
    ('CO_21', 'CO', 'Denver', 'Playco Park Builders Inc.'),
    ('CO_22', 'CO', 'Arvada', 'Harper Brothers Construction Inc.'),
    ('CO_23', 'CO', 'Englewood', 'Rocky Mountain Construction Company'),
    ('CO_24', 'CO', 'Denver', 'H & L CONSTRUCTION COMPANY'),
    ('CO_25', 'CO', 'Denver', 'MC2 ELECTRICAL CONTRACTORS LLC'),
    ('CO_26', 'CO', 'Denver', 'Hoffman/Weber Construction, LLC'),
    ('CO_27', 'CO', 'Centennial', 'KUPONO CONSTRUCTION, INC.'),
    ('CO_28', 'CO', 'Aurora', 'Absolute Concrete Flooring, Inc.'),
    ('CO_29', 'CO', 'Arvada', 'A. P. Plumbing'),
    ('CO_30', 'CO', 'Centennial', 'DREAM MAKERS CONSTRUCTION, LLC'),
    ('CO_31', 'CO', 'Lakewood', 'Dave''s Landscape & Construction, Inc.'),
    ('CO_32', 'CO', 'Centennial', 'THORSEN CONSTRUCTION, LLC'),
    ('CO_33', 'CO', 'Aurora', 'Avi''s Remodeling and Contracting, LLC'),
    ('CO_34', 'CO', 'Lakewood', 'DECOSTAMP CONCRETE CO.'),
    ('CO_35', 'CO', 'Denver', 'REDSTONE CONSTRUCTION, INC.'),
    ('CO_36', 'CO', 'Aurora', 'Affordable Flooring & Remodeling, Inc.'),
    ('CO_37', 'CO', 'DENVER', 'MIGHTY EARTHWORKS LLC'),
    ('CO_38', 'CO', 'Lakewood', 'INTEGRITY FINISHES AND CONSTRUCTION, INC.'),
    ('CO_39', 'CO', 'ENGLEWOOD', 'CIMARRON BUILDERS, INC.'),
    ('CO_40', 'CO', 'Denver', 'O''BRIEN CONCRETE PUMPING, LLC'),
    ('CO_41', 'CO', 'Wheat Ridge', 'Absolute Caulking & Waterproofing Inc.'),
    ('CO_42', 'CO', 'Denver', 'AXIOM CONSTRUCTION, INC.'),
    ('CO_43', 'CO', 'Wheat Ridge', 'OMNI CUSTOM BUILDERS, INC.'),
    ('CO_44', 'CO', 'Lakewood', 'EDGE CONSTRUCTION SPECIALTIES, INC.'),
    ('CO_45', 'CO', 'Lakewood', 'RECONSTRUCTION EXPERTS, INC.'),
    ('CO_46', 'CO', 'Wheat Ridge', 'WESTERN ROOFING, INC.'),
    ('CO_47', 'CO', 'Lakewood', 'BRAGDON CONSTRUCTION INC.'),
    ('CO_48', 'CO', 'Denver', 'CENTRAL ROOFING SERVICE, INC.'),
    ('CO_49', 'CO', 'Centennial', 'Graham Love Construction, LLC'),
    ('TX_00', 'TX', 'MANSFIELD', '1776 DEVELOPMENT AND CONSTRUCTION INC.'),
    ('TX_01', 'TX', 'BEDFORD', 'JENNY CONSTRUCTION, INC.'),
    ('TX_02', 'TX', 'FORT WORTH', 'ALLEN''S CONTRACTING, INC.'),
    ('TX_03', 'TX', 'ARLINGTON', 'THE RANCH CONSTRUCTION MATERIALS 5 LLC'),
    ('TX_04', 'TX', 'EVERMAN', 'TRI-LAM ROOFING & WATERPROOFING, INC.'),
    ('TX_05', 'TX', 'FORT WORTH', 'TOP CREW CONSTRUCTION LLC'),
    ('TX_06', 'TX', 'CEDAR HILL', 'COVENANT COMMERCIAL CONSTRUCTION, LLC'),
    ('TX_07', 'TX', 'KELLER', 'BLUE STARR CONSTRUCTION GROUP, LLC'),
    ('TX_08', 'TX', 'FORT WORTH', 'LAZY K CONTRACTING LLC'),
    ('TX_09', 'TX', 'PRINCETON', 'RANCH HAND CONTRACTING LLC'),
    ('TX_10', 'TX', 'GARLAND', 'WALTER CONSTRUCTION  INC.'),
    ('TX_11', 'TX', 'DALLAS', 'OP CONTRACTING GA, LLC'),
    ('TX_12', 'TX', 'DALLAS', 'SPEARMAN CUSTOM BUILDERS, INC.'),
    ('TX_13', 'TX', 'ALLEN', 'HDT-CONSTRUCTION LLC'),
    ('TX_14', 'TX', 'PLANO', 'WIND & WATER CONSTRUCTION, LLC'),
    ('TX_15', 'TX', 'HURST', 'BUILDERS PROCLIVITY LLC'),
    ('TX_16', 'TX', 'GARLAND', 'PRONTO CONCRETE LLC'),
    ('TX_17', 'TX', 'ARLINGTON', 'AGUILAR LANDSCAPING AND CONSTRUCTION, LLC'),
    ('TX_18', 'TX', 'ROANOKE', 'TROPHY ROOFING & CONSTRUCTION LLC'),
    ('TX_19', 'TX', 'FORT WORTH', 'RETZLAFF CONSTRUCTION, LLC'),
    ('TX_20', 'TX', 'FORT WORTH', 'GEARHEART CONSTRUCTION CO., INC.'),
    ('TX_21', 'TX', 'DALLAS', 'BREWSTER ELECTRIC AND CONSTRUCTION LIMITED LIABILI'),
    ('TX_22', 'TX', 'ALLEN', 'BAUG CONSTRUCTION CORPORATION'),
    ('TX_23', 'TX', 'HASLET', 'CASTLE HILL BUILDERS LLC'),
    ('TX_24', 'TX', 'MESQUITE', 'JFC PLUMBING CORPORATION'),
    ('TX_25', 'TX', 'DALLAS', 'NIELSEN PLUMBING SERVICES, INC.'),
    ('TX_26', 'TX', 'ARLINGTON', 'RIGHT CHOICE CONSTRUCTION AND RESTORATION LLC'),
    ('TX_27', 'TX', 'MANSFIELD', 'REIGN OUT ROOFING LLC'),
    ('TX_28', 'TX', 'ANNA', 'HAYES CUSTOM CONTRACTING LLC'),
    ('TX_29', 'TX', 'DALLAS', 'G BROTHERS RESTORATION & HOME REMODELING LLC'),
    ('TX_30', 'TX', 'DALLAS', 'FONSECA REMODELING, LLC'),
    ('TX_31', 'TX', 'FRISCO', 'ASCEND ROOFING LLC'),
    ('TX_32', 'TX', 'DALLAS', 'BARRERA PLUMBING, L.L.C.'),
    ('TX_33', 'TX', 'COPPELL', 'INGRAM CONSTRUCTION GROUP, LLC'),
    ('TX_34', 'TX', 'GARLAND', 'BNC GENERAL CONTRACTING AND RESTORATION LLC'),
    ('TX_35', 'TX', 'CEDAR HILL', 'BALCARCEL''S HOME BUILDERS, LLC'),
    ('TX_36', 'TX', 'FORT WORTH', 'AREVALO DOUBLE H CONSTRUCTION LLC'),
    ('TX_37', 'TX', 'ARLINGTON', 'ONE CROSS ROOFING AND RENOVATIONS LLC'),
    ('TX_38', 'TX', 'DALLAS', 'TASHA CONSTRUCTION CO'),
    ('TX_39', 'TX', 'MCKINNEY', 'MEL JARAMILLO REMODELING LLC'),
    ('TX_40', 'TX', 'FORT WORTH', 'JR CONCRETE CUTTING  L.L.C.'),
    ('TX_41', 'TX', 'LEWISVILLE', 'QRO CONCRETE CORPORATION'),
    ('TX_42', 'TX', 'DALLAS', 'ELITE PAVING ACQUISITIONS, LLC'),
    ('TX_43', 'TX', 'SOUTHLAKE', 'NUVIDA BUILDERS LLC'),
    ('TX_44', 'TX', 'NORTHLAKE', 'NEW DAWN COMMERCIAL CONTRACTING LLC'),
    ('TX_45', 'TX', 'ARLINGTON', 'BURRESS PLUMBING SOLUTIONS, LLC'),
    ('TX_46', 'TX', 'GARLAND', 'RL CONSTRUCTION & INVESTMENTS LLC'),
    ('TX_47', 'TX', 'COPPELL', 'LAZAROSKI CONSTRUCTION LIMITED LIABILITY COMPANY'),
    ('TX_48', 'TX', 'DALLAS', 'GV LANDSCAPE AND CONSTRUCTION LLC'),
    ('TX_49', 'TX', 'ROWLETT', 'TUCKER ROOFING SYSTEMS LLC')
)
SELECT
  p.label,
  p.contractor_name,
  e.id AS job_id,
  e.contractor_id,
  e.status
FROM params p
CROSS JOIN LATERAL enqueue_trust_job(
  p_contractor_name := p.contractor_name,
  p_state_code := p.state,
  p_city := p.city,
  p_tier := 'standard',
  p_user_id := NULL,
  p_credit_id := NULL,
  p_idempotency_key := 'DATAPIECE_1777821831_' || p.label
) e
ORDER BY p.label;